// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMTGALclzOpo-0wLaVmq42jQ6wjumvvE',
    appId: '1:965490073927:web:c5642d118bb35359d1ec62',
    messagingSenderId: '965490073927',
    projectId: 'compass-pro-7d0a6',
    authDomain: 'compass-pro-7d0a6.firebaseapp.com',
    storageBucket: 'compass-pro-7d0a6.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGMTGALclzOpo-0wLaVmq42jQ6wjumvvE',
    appId: '1:965490073927:android:c5642d118bb35359d1ec62',
    messagingSenderId: '965490073927',
    projectId: 'compass-pro-7d0a6',
    storageBucket: 'compass-pro-7d0a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGMTGALclzOpo-0wLaVmq42jQ6wjumvvE',
    appId: '1:965490073927:ios:c5642d118bb35359d1ec62',
    messagingSenderId: '965490073927',
    projectId: 'compass-pro-7d0a6',
    storageBucket: 'compass-pro-7d0a6.firebasestorage.app',
    iosBundleId: 'com.primio.truenorth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGMTGALclzOpo-0wLaVmq42jQ6wjumvvE',
    appId: '1:965490073927:ios:c5642d118bb35359d1ec62',
    messagingSenderId: '965490073927',
    projectId: 'compass-pro-7d0a6',
    storageBucket: 'compass-pro-7d0a6.firebasestorage.app',
    iosBundleId: 'com.primio.truenorth',
  );
}
